name: Vulnerable Script Injection

on:
  pull_request:
  issues:

jobs:
  vulnerable-script-injection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Vulnerable to script injection via PR title/body
      - name: Echo PR details
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "PR body: ${{ github.event.pull_request.body }}"
          echo "Issue title: ${{ github.event.issue.title }}"
      
      # Vulnerable to script injection via environment variable
      - name: Process user input
        run: echo "Hello $USER_NAME"
        env:
          USER_NAME: ${{ github.event.pull_request.user.login }}