name: Vulnerable Secrets Exposure

on:
  pull_request:
  push:

jobs:
  expose-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Accidentally exposing secrets in logs
      - name: Debug environment
        run: |
          echo "API Key: ${{ secrets.API_KEY }}"
          echo "Database URL: ${{ secrets.DATABASE_URL }}"
          env | grep SECRET
      
      # Passing secrets to untrusted actions
      - uses: some-third-party/log-everything@v1
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          
      # Writing secrets to files that might be uploaded
      - name: Create config file
        run: |
          cat > config.json << EOF
          {
            "api_key": "${{ secrets.API_KEY }}",
            "database_url": "${{ secrets.DATABASE_URL }}"
          }
          EOF
          
      - uses: actions/upload-artifact@v4
        with:
          name: config
          path: config.json  # Uploading secrets as artifact