name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3

      - name: install zizmor
        run: |
          uv tool install zizmor

      - name: install gh-zizmor extension
        run: |
          gh extension install .

      - name: verify it works
        run: |
          gh zizmor --version

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - file: secure-docker-build.yml
          - file: secure-example.yml
          - file: secure-release.yml

          - file: vulnerable-permissions.yml
          - file: vulnerable-script-injection.yml
          - file: vulnerable-secrets-exposure.yml
          - file: vulnerable-third-party-actions.yml
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3

      - name: install zizmor
        run: |
          uv tool install zizmor

      - name: install gh-zizmor extension
        run: |
          gh extension install .

      - name: verify it works
        run: |
          gh zizmor --version

      - name: run zizmor analysis
        env:
          FILE: ${{ matrix.file }}
        run: |
          gh zizmor ./workflow-tests/$FILE
